name: c r y p t o p u n k s
meta_description: "Всё о компьютерной безопасности и анонимном пребывании в сети"

#markdown: kramdown #redcarpet
markdown: redcarpet

redcarpet:
     extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
    #  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#pygments: true
#
highlighter: true
logo: false
paginate: 15
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]
permalink: /:categories/:title/
#relative_permalinks: true
timezone: 'Europe/Moskow'

# Details for the RSS feed generator
url:            'https://cryptopunks.org'
#author:         'soko1'
baseurl:   '/'
