name: c r y p t o p u n k s
meta_description: "Всё о компьютерной безопасности и анонимном пребывании в сети"

markdown: kramdown #redcarpet

plugins:
        - jekyll-feed
        - jekyll-paginate
        - jekyll-gist
        - jekyll-sitemap
  
highlighter: true
logo: false
paginate: 15
permalink: /:categories/:title/
#relative_permalinks: true
timezone: 'Europe/Moskow'

# Details for the RSS feed generator
url:            'https://cryptopunks.org'
#author:         'soko1'
baseurl:   '/'
